# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a5e566e734b59e760c3f03c26b722941500a612136ca6a5a3f6d2649212abc952b704e9ce4d035147a108dc82d3ac1844bb6603c3cd7642a65d093ebb4a6bed

test:
  secret_key_base: d56f3f708b6e2ef5e7b1debfe173eb2ce3e8214379ed4e8ff58f1932a398cfcb521b6604b689df48d863430821b84f5b7519409c1dfb0e051b7d9ed96696d06e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
